Add weaponsto backpack
gruppe-adler/grad-loadout.fork pull request #35
Opened 2018-11-02 19:44 UTC by AdlerSalbei

2018-11-03 20:49 UTC, McDiod requested changes

2018-11-03 20:49 UTC, McDiod commented on functions/extract/fn_extractLoadoutFromConfig.sqf
> +            private _scope = [_configPath >> _x >> "scope", "text", ""] call  CBA_fnc_getConfigEntry;
```suggestion
            private _scope = [_configPath >> _x >> "optics", "text", ""] call  CBA_fnc_getConfigEntry;
```

Let's call this "optics" to be consistent with `primaryWeaponOptics` etc.

2018-11-03 20:49 UTC, McDiod commented on functions/extract/fn_extractLoadoutFromConfig.sqf
> +                private _scope = [_configPath >> _x >> "scope", "text", ""] call  CBA_fnc_getConfigEntry;
```suggestion
                private _scope = [_configPath >> _x >> "optics", "text", ""] call  CBA_fnc_getConfigEntry;
```

see above

2018-11-03 20:49 UTC, McDiod commented on README.md
> +    scope = "";
```suggestion
    optics = "";
```

see above

2018-11-03 20:49 UTC, McDiod commented on README.md
> +    scope = "";
```suggestion
    optics = "";
```

see above

2018-11-03 20:49 UTC, McDiod commented on functions/general/fn_normalizeContent.sqf
> +private _backpackClass = (_unitLoadout select 5) select 0;
`_backpackClass` is unused in this function, which also means we don't need the `_unitLoadout` that is passed to it.

2018-11-03 20:49 UTC, McDiod commented on functions/general/fn_hashToUnitLoadout.sqf
> +                _value = [_value, _unitLoadout] call _classNameToPickOrMapper;
See above - `_unitLoadout` is apparently not needed in fn_normalizeContent.

2018-11-03 20:49 UTC, McDiod commented on README.md
> +If you want to use a weapon in a backpack, the config has to look like the following:
```suggestion
If you want to add a weapon to a backpack, simply add the weapon's classname to `addItemsToBackpack` like you would with any other item. However, if you want the weapon to have attachments and/or loaded magazines, the config has to look like this:
```

2018-11-03 21:03 UTC, McDiod approved these changes

2018-11-03 21:20 UTC, DerZade approved these changes
Looks good to me :D
Nicely done @AdlerSalbei

2018-11-03 21:20 UTC, McDiod commented on README.md
> +If you want to add a weapon to a backpack, simply add the weapon's classname to `addItemsToBackpack` like you would with any other item. However, if you want the weapon to have attachments and/or loa
```suggestion
If you want to add a weapon to a backpack, simply add the weapon's classname to `addItemsToBackpack` like you would with any other item. However, if you want the weapon to have attachments and/or loaded magazines, the config has to look like the following examples. Note that the weapon class has to be inside the same parent class as the `addItemsToBackpack` property where it is used.
```

@DerZade  so?

2018-11-03 21:23 UTC, DerZade approved these changes

2018-11-03 22:04 UTC, merged

2018-11-04 00:59 UTC, dedmen commented on functions/general/fn_normalizeContent.sqf
> +    if ((typeName _x) == "ARRAY") then {
`isEqualType`