customGear v2
gruppe-adler/grad-loadout.fork pull request #46
Opened 2019-10-24 18:24 UTC by McDiod

Aims to replace [grad-customGear](https://github.com/gruppe-adler/grad-customGear) by integrating it directly into grad-loadout. Loadout selection options will be based on randomized items, e.g.:

```
// After loadout application, unit will be able to choose between two uniforms.
uniform[] = {"U_C_man_sport_1_F", "U_BG_Guerilla2_1"};
headgear = "SMM_Helmet_A_BW_FT";
primaryWeapon = "rhs_weap_hk416d10";
```

Configuration options are:

```
class Loadouts {
    customGear = 300;
};
```

Where `customGear` can be 
* -1 to disable
* any number for a timeout in seconds after loadout application where loadout can be customized, or 
* a statement (params: [unit]) that has to return true for the unit to be able to use loadout customization, e.g. `"(_this select 0) distance2D (getMarkerPos "respawn_west") < 100"`.

2019-10-31 19:36 UTC, McDiod commented
Current status:

https://youtu.be/qrs8Sx662c4

ToDo:

- [ ] config options for enabling / disabling categories
- [ ] functions for enabling / disabling single units
- [ ] function for adding interaction to object instead of using self-interaction
- [ ] update readme.md

2019-11-01 13:36 UTC, McDiod commented
Ready for review. I will add documentation as GitHub Pages after merging, because the readme is getting too big. Added some documentation to the OP for now.

2019-11-04 23:14 UTC, nomisum approved these changes

2019-11-05 09:19 UTC, AdlerSalbei commented on functions/customgear/fn_initCustomGear.sqf
> +        [{(missionNamespace getVariable ["CBA_missionTime",0]) > 10 && {[_this] call GVAR(customGearCondition)}}, {
```suggestion
        [{(missionNamespace getVariable ["CBA_missionTime", 0]) > 10 && {[_this] call GVAR(customGearCondition)}}, {
```

2019-11-05 09:20 UTC, AdlerSalbei commented on functions/customgear/fn_initCustomGear.sqf
> +                ["GRAD_saveMarkers_notification",["GRAD CUSTOM GEAR","Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
```suggestion
                ["GRAD_saveMarkers_notification", ["GRAD CUSTOM GEAR", "Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
```

2019-11-05 09:20 UTC, AdlerSalbei commented on functions/customgear/fn_initCustomGear.sqf
> +                ["TaskUpdated",["","Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
```suggestion
                ["TaskUpdated", ["", "Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
```

2019-11-05 09:32 UTC, Salbei2500 requested changes
In getcurrentItem nutzt du 
`{uniform _unit},
{vest _unit},
{backpack _unit},` und in onCustomGearListSelection benutzt du ` {(_unitLoadout select 4) set [0, _itemClassname]}`. Denkst du nicht es wäre schlauer das eine oder das andere zu nutzen?

2019-11-05 10:43 UTC, nomisum commented on functions/customgear/fn_initCustomGear.sqf
> +                ["TaskUpdated",["","Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
spacenatic?

2019-11-05 10:57 UTC, AdlerSalbei commented on functions/customgear/fn_initCustomGear.sqf
> +                ["TaskUpdated",["","Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
Ordnung muss sein

2019-11-05 11:00 UTC, nomisum commented on functions/customgear/fn_initCustomGear.sqf
> +                ["TaskUpdated",["","Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
Aus welchen Guidelines ist das? ACE? Wirkt für mich unnötig an der Stelle.

2019-11-05 11:24 UTC, AdlerSalbei commented on functions/customgear/fn_initCustomGear.sqf
> +                ["TaskUpdated",["","Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
Er hat überall anders nen " " nach dem , da macht es das einfach lesbarer.

2019-11-05 15:55 UTC, McDiod commented on functions/customgear/fn_initCustomGear.sqf
> +                ["TaskUpdated",["","Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
Ich mach das normalerweise auch nicht, hab hier versucht Fussels Stil weiterzuführen und es an manchen Stellen vergessen anscheinend.

2019-11-05 15:58 UTC, McDiod commented
> In getcurrentItem nutzt du
> `{uniform _unit}, {vest _unit}, {backpack _unit},` und in onCustomGearListSelection benutzt du ` {(_unitLoadout select 4) set [0, _itemClassname]}`. Denkst du nicht es wäre schlauer das eine oder das andere zu nutzen?

Ja, ist mir beim Schreiben auch schon aufgefallen. Irgendwas war da in der getCurrentItem Funktion, dass bei `getUnitLoadout` die einzelnen Classnames nicht immer an der gleichen Stelle im Array stehen, wenn die Einheit manche Loadoutgegenstände gar nicht hat?

2019-11-05 16:23 UTC, nomisum commented on functions/customgear/fn_initCustomGear.sqf
> +                ["TaskUpdated",["","Loadout customization now available. (Selfinteract >> Equipment)"]] call BIS_fnc_showNotification;
ah... ich würde den call vom biki kopieren und damit wärn schonma keine drin 😁 

wenn ich übersichtlichkeit möchte mach ich dann eher n zeilenumbruch.

2019-11-05 18:58 UTC, Fusselwurm approved these changes
👍 

wenn ich mir was wünschen darf: diese ganzen _keyId - Listen sind alle gleich, oder? irgendwie würd ich die in ne eigene globale variable packen, oder ein macro, wenns sein muß

2019-11-05 19:38 UTC, McDiod commented
Guter Punkt, ist jetzt in
https://github.com/gruppe-adler/grad-loadout/blob/customGear/functions/customgear/component.hpp

2019-11-07 15:18 UTC, closed without merging